# Site settings
title: Charityware Engineering
description: "A minimal blog template, build with Jekyll."
url: "https://charityware.github.io/"
author:
  name: "Mark Thomas"
  email: "hello@charityware.co"
  url: "https://charityware.co"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:categories/:year/:month/:day/:title/
paginate: 4
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.2.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
